seed: 42
device: auto

data:
  file_dir: "/content/AI/LLM_research_platform/src/data/input_data/data/token_training/"
  local_file_path:  "/Users/chaofang/Documents/coding_playground/GitHub/AI/LLM_research_platform/src/data/input_data/data/"
  local_index_path:  "/Users/chaofang/Documents/coding_playground/GitHub/AI/LLM_research_platform/src/data/input_data/data/index_files/"
  colab_file_path: "/content/AI/LLM_research_platform/src/data/input_data/data/"
  colab_index_path: "/content/AI/LLM_research_platform/src/data/input_data/data/index_files/
  max_len: 256
  batch_size: 8
  validation_batch_size: 128
  shuffle: true

tokenizer:
  vocab_size: 10000
  pattern: gpt2

model:
  d_model: 384
  n_layers: 6
  n_heads: 6
  rope: True
  rope_dims: [64]
  dropout: 0.2
  mlp_ratio: 4
  cross_attention: False
  causal: True

training:
  epochs: 100
  learning_rate: 0.0003
  weight_decay: 0.01
  accumulation_steps: 8
  max_grad_norm: 1.0
  training_file: "training.txt"
  validation_file: "validation.txt"

logging:
  enabled: true
  project: my-gpt
  log_every_batches: 100
  print_every_batches: 250